language: ruby
rvm: 2.2.2
sudo: false

before_install:
 - gem install hiptest-publisher
 - "hiptest-publisher -c cucumber.conf --token=$SECRET_TOKEN --only=features,step_definitions --test-run-id=3507"

script:
 - bundle exec cucumber --format junit --out results

after_script:
  - hiptest-publisher -c cucumber.conf --token=$SECRET_TOKEN --push="results/*.xml" --test-run-id=3507
